(setq package-user-dir "~/.emacs.d/elpa")
(message "Current directory: %s" default-directory)
(require 'package)
(package-refresh-contents)
(message "\nInstall Loopy from dir:")
(package-install-file (expand-file-name "loopy/" default-directory))
(message "\nInstall Loopy Dash from file:")
(package-install-file (expand-file-name "loopy-dash/loopy-dash.el" default-directory))
