name: Test Emacs Matrix
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    name: 'Install and Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          # - '27.1'
          - '27.2'
          # - '28.1'
          - '28.2'
          - '29.2'
          - 'release-snapshot'
          # - 'snapshot'
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: Print working directory
      run: echo "Current working directory is $PWD"
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Make config dir to guarantee location.  Do it before we run Emacs the first time.
      run: mkdir ~/.emacs.d
    - name: Check Emacs version
      run: emacs --version
    - name: Make Tar file of base package
      run: make tar
    - name: Get Loopy Dash from new repo
      run: git clone 'https://github.com/okamsn/loopy-dash.git' ./loopy-dash
    - name: Install package Loopy
      run: emacs -batch -l tests/install-script.el
    - name: Test accessing Info data
      run: emacs -batch --eval='(progn (package-activate-all) (info "(loopy)Top"))'
    - name: Basic tests
      run: emacs -batch --eval='(package-activate-all)' -l ert -l tests/tests.el -f ert-run-tests-batch-and-exit
    - name: Seq tests
      run: emacs -batch --eval='(package-activate-all)' -l ert -l tests/seq-tests.el -f ert-run-tests-batch-and-exit
    - name: Pcase tests
      run: emacs -batch --eval='(package-activate-all)' -l ert -l tests/pcase-tests.el -f ert-run-tests-batch-and-exit
    - name: Iter tests
      run: emacs -batch --eval='(package-activate-all)' -l ert -l tests/iter-tests.el -f ert-run-tests-batch-and-exit
    - name: Dash tests
      run: emacs -batch --eval='(package-activate-all)' -l ert -l loopy-dash/tests/dash-tests.el -f ert-run-tests-batch-and-exit
    - name: Miscellaneous tests
      run: emacs -batch --eval='(package-activate-all)' -l ert -l tests/misc-tests.el -f ert-run-tests-batch-and-exit
    - run: echo "🍏 This job's status is ${{ job.status }}."
